### ISSUE TITLE
DataModel: adaptions

### ISSUE THREAD

**Issue by ovgu-ubit** [ovgu-ubit/output#31]

**Comment by bossanova1986** [comment]
*	Publikation
	*	Herausgeberschaft
	*	Abstract
	*	Zitationsangabe (je nach Typ enthält dieser z.B. Auflage, Verlagsort, Heft, Band, Seitenangaben)
	*	Seitenzahl
	*	Datum der Akzeptanz
	*	Datum der Printveröffentlichung
	*	Peer-reviewed
	*	Beste OA-Lizenz
	*	Mögliche Lizenzen als eigene Entität modellieren
*	Autor
	*	GND
*	Größere Einheit
	*	Im DOAJ seit
	*	Im DOAJ bis
*	Förderer
	*	ROR-ID

**Comment by bossanova1986** [comment]
- [ ] enable data fields by config

**Comment by bossanova1986** [comment]
* ISO-Standards für Stammdaten nutzen
   * Sprache (Top 5)
   * Originalwährung (Top 5 ohne EUR)
* Anpassung Bezeichnung Rechnung
   * Nettobetrag in Euro
   * Nettobetrag in Originalwährung

**Comment by bossanova1986** [comment]
#37
